# Generated by Django 3.0.8 on 2020-08-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliceapp', '0002_answer_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='surbey_idx',
            new_name='survey_idx',
        ),
    ]
