# Generated by Django 3.0.8 on 2020-09-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliceapp', '0003_auto_20200813_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
